// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9cacb157-90d1-40b7-b545-67d4552bde7b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_TKduzYnmG",
    "aws_user_pools_web_client_id": "1e9bml1iclt1o3jf88uf88cj6m",
    "oauth": {
        "domain": "efohkf3917302-f3917302-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "email",
            "openid"
        ],
        "redirectSignIn": process.env.REACT_APP_COGNITO_REDIRECT,
        "redirectSignOut": process.env.REACT_APP_COGNITO_REDIRECT,
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
